all: libhxmoveapi.so hxmoveapi.o

libhxmoveapi.so: hxmoveapi.o
	gcc -shared -fPIC -o lib/libhxmoveapi.so lib/hxmoveapi.o -lc -L lib/linux -lpsmoveapi

hxmoveapi.o: hxmoveapi.cpp
	g++ -c -fPIC -o lib/hxmoveapi.o hxmoveapi.cpp

.PHONY: all