all: hxmoveapi.dll

hxmoveapi.dll: hxmoveapi.obj
	cl /LD /MD /Felib\hxmoveapi.dll "lib\hxmoveapi.obj" "lib\win\psmoveapi.lib"

hxmoveapi.obj: hxmoveapi.cpp
	cl /c /MD /Folib\hxmoveapi.obj hxmoveapi.cpp

.PHONY: all