all: libhxmoveapi.dylib hxmoveapi.o

libhxmoveapi.dylib: hxmoveapi.cpp
	gcc -dynamiclib -o libhxmoveapi.dylib hxmoveapi.cpp

libhxmoveapi.so: hxmoveapi.o
	gcc -shared -fPIC -o lib/libhxmoveapi.so lib/hxmoveapi.o -lc -L lib/osx -lpsmoveapi

hxmoveapi.o: hxmoveapi.cpp
	g++ -c -fPIC -o lib/hxmoveapi.o hxmoveapi.cpp

.PHONY: all