version: '3'
services:
  linux:
    build:
      context: .
      dockerfile: Dockerfile.linux
    volumes: 
      - ./container_volume:/usr/local/share/host
  win:
    build:
      context: .
      dockerfile: Dockerfile.win
    volumes: 
      - ./container_volume:c:\host